---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: directory
    path: src/content
    label: Pages
    create: all
    match: "*"
  - type: directory
    path: src/content/blog
    label: Blog
    create: documents
    match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
version: 0.81.0
